name: Release latest version
on:
  push:
    branches:
      - "master"

jobs:
  auto-release:
    runs-on: ubuntu-latest
    steps:
      - name: Setup repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: Get release version
        id: get-version
        run: |
          export PACKAGE_VERSION=$(cat package.json | grep 'version' | sed 's/[ \",:]//g' | sed 's/version//')
          echo "::set-output name=version::$PACKAGE_VERSION"
      - name: Get previous version
        id: prev-version
        uses: WyriHaximus/github-action-get-previous-tag@v1
      - name: Exit if not new version
        if: ${{ steps.get-version.outputs.version == steps.prev-version.outputs.tag }}
        run: exit 1
      - name: Install otftotfm
        run: sudo apt-get install -y lcdf-typetools
      - name: Use Node.js 16.x
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - name: Install dependendies
        run: yarn
      - name: Run script
        run: node bindings.js
      - name: Compile doc
        uses: xu-cheng/latex-action@v2
        with:
          root_file: simpleicons.tex
      - name: Make directories
        run: mkdir -p simpleicons simpleicons/{doc,enc,map,opentype,tex,tfm,type1}
      - name: Move files
        run: |
          cp README.md simpleicons
          mv -t simpleicons/doc simpleicons.pdf simpleicons.tex bindings.tex
          mv *.enc simpleicons/enc
          mv simpleicons.map simpleicons/map
          mv SimpleIcons.otf simpleicons/opentype
          mv -t simpleicons/tex simpleicons.sty *glyphs-*.tex *.fd
          mv *.tfm simpleicons/tfm
          mv SimpleIcons.pfb simpleicons/type1
      - name: Create archive
        working-directory: simpleicons
        run: zip -r ../simpleicons.zip ./*
      - uses: paolobrasolin/ctan-submit-action@v1
        with:
          file_path: simpleicons.zip
          fields: |
            pkg: simpleicons
            version: ${{ steps.get-version.outputs.version }}
            author: Inesh Bose
            email: Inesh.Bose@glasgow.ac.uk
            uploader: Inesh.Bose@glasgow.ac.uk
            license: CC0-1.0
            summary: Update version
      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          name: v${{ steps.get-version.outputs.version }}
          tag_name: ${{ steps.get-version.outputs.version }}
          body: |
            See https://github.com/simple-icons/simple-icons/releases/tag/${{ steps.get-version.outputs.version }}
          files: |
            simpleicons.zip
            simpleicons.pdf
